<h1>Registration </h1>
<?php echo $this->escapeHtml($this->messages); ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'Registration', 'action' => 'Index')));
$form->prepare();
echo $this->form()->openTag($form);

?>
<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('email')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password'));  ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('password_confirm'));  ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('captcha'));  ?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>