<?php
/**
 * Created by PhpStorm.
 * User: Zeeshan
 * Date: 6/5/2017
 * Time: 1:05 AM
 */

$title = 'Create User';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php


$form->setAttribute('action', $this->url('user', array('action' => 'create')));
$form->prepare();




    echo $this->form()->openTag($form);?>
<div class="form-group">

        <?php echo $this->formHidden($form->get('id')); ?>

</div>

<div class="form-group">

        <?php echo $this->formRow($form->get('name'));?>



</div>


<div class="form-group">

        <?php echo $this->formRow($form->get('email'));  ?>



</div>

<div class="form-group">

        <?php echo $this->formRow($form->get('address'));  ?>


</div>

   <div class="form-group">

           <?php echo $this->formRow($form->get('mobile'));  ?>



   </div>




  <?php
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>





