<?php
/**
 * Created by PhpStorm.
 * User: Zeeshan
 * Date: 6/5/2017
 * Time: 1:06 AM
 */



 $title = 'Delete User';
 $this->headTitle($title);

 ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($User->name); ?>' by
    '<?php echo $this->escapeHtml($User->email); ?>'?
</p>
<?php
$url = $this->url('user', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $User->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>